<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/11/1
 * Time: 16:24
 */

namespace app\controllers;

use UpYun;



class AdminuserController extends BackController
{
    private $picKey = "";
    private $userInfo = array();
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->userInfo = $this->session->get("admin");
        if(!$this->userInfo){
            $this->redirect(Url::to(['adminlogin/loginadmin']));
        }
    }

    /*
     * 后台登陆
     */

    public function actionIndex()
    {

        return $this->render("index");
    }

    /*
     * 所有账号
     */
    public function actionUserlist()
    {

        return $this->render("userlist");
    }

    /*
     * 上传图片
     */
    public function actionFateup()
    {
        $controllerID = \Yii::$app->controller->id;
        echo $controllerID;
        return $this->render("fateup");
    }

    /*
     * ajax上传图片
     */
    public function actionAjaxuploadfile()
    {
        $bucket = \Yii::$app->params['bucket'];
        $operator = \Yii::$app->params['upyunuser'];
        $password = \Yii::$app->params['uoyunpassword'];
        $type = $_REQUEST['type'];

        $up = new Upyun($bucket,$operator,$password);
        $file = fopen($_FILES['inputfa']['tmp_name'][0],'r');
        $hz = $this->get_extension($_FILES['inputfa']['name'][0]);
        if($type){
            $path = "/".$type."/".md5(time().$_FILES['inputfa']['name'][0]).".".$hz;
        }
        $res = $up->writeFile($path,$file);
        if($res){
            $redis = Yii::$app->redis;
            
            echo json_encode(array("code"=>10000,"msg"=>"上传成功","picurl"=>\Yii::$app->params['picurl'].$path));exit;
        }else{
            echo json_encode(array("code"=>10001,"msg"=>"上传失败"));exit;
        }
        exit;
    }

    /*
     * 获取后缀
     */
    function get_extension($file)
    {
        $info = pathinfo($file);
        return $info['extension'];
    }
}