<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/11/4
 * Time: 14:48
 */

namespace app\controllers;


use app\models\Admin_user;

class AdminloginController extends BackController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this ->layout = false;
        $this->enableCsrfValidation=false;
    }

    /*
     * 验证码
     */
    public function actions() {
        return [
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'maxLength' => 4,
                'minLength' => 4
            ],
        ];
    }


    /*
     * 后台登陆
     */
    public function actionLoginadmin()
    {

        return $this->render("login");
    }

    /*
     * 执行后台登陆
     */
    public function actionDoadminlogin()
    {
        $admin_user = new Admin_user();
        $captchCode = $_POST['vcode'];
        $res = $this->createAction('captcha')->validate($captchCode, false); //$captchCode为用户输入的验证码
        if($res){
            $str = "<script>alert('验证码错误');</script>";
            $this->redirect("adminlogin/loginadmin",$str);
            exit;
        }
        $adminUserName = $_POST['username'];
        $password = $_POST['password'];
        $data = array(
            'username' => $adminUserName,
            'password' => $password,
        );
        $userRes = $admin_user->verAdminUser($data);
        if($userRes){
            $str = "<script>alert('登陆成功');</script>";
            $this->redirect("adminuser/index",$str);
            exit;
        }else{
            $str = "<script>alert('登陆失败,用户名或密码错误');</script>";
            $this->redirect("adminuser/index",$str);
            exit;
        }
    }
}