<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/11/4
 * Time: 14:48
 */

namespace app\controllers;


use app\models\Admin_user;

class AdminloginController extends BackController
{
    public function init()
    {
        header("Content-type: text/html; charset=utf-8");
        parent::init(); // TODO: Change the autogenerated stub
        $this ->layout = false;
        $this->enableCsrfValidation=false;
    }

    /*
     * 验证码
     */
    public function actions() {
        return [
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'maxLength' => 4,
                'minLength' => 4,
                'testLimit' => 1,
            ],
        ];
    }


    /*
     * 后台登陆
     */
    public function actionLoginadmin()
    {



        return $this->render("login");
    }

    /*
     * 执行后台登陆
     */
    public function actionDoadminlogin()
    {
        $admin_user = new Admin_user();
        $captchCode = $_POST['vcode'];
        if($captchCode == ''){
            $str = "<script>alert('验证码不能为空');location.href='/adminlogin/loginadmin';</script>";
            echo $str;
            exit;
        }
        $str = "__captcha/adminlogin/captcha";
         //$captchCode为用户输入的验证码
        if($_SESSION[$str] != $captchCode){
            $str = "<script>alert('验证码错误');location.href='/adminlogin/loginadmin';</script>";
            echo $str;
            exit;
        }
        $adminUserName = $_POST['username'];
        $password = $_POST['password'];
        if(empty($adminUserName) || empty($password)){
            $str = "<script>alert('用户名或密码不能为空');location.href='/adminlogin/loginadmin';</script>";
            echo $str;
            exit;
        }
        $data = array(
            'username' => $adminUserName,
            'password' => md5($password),
        );
        $userRes = $admin_user->verAdminUser($data);
        if($userRes){
            $str = "<script>alert('登陆成功');location.href='/adminuser/index';</script>";
            echo $str;
            exit;
        }else{
            $str = "<script>alert('登陆失败,用户名或密码错误');location.href='/adminlogin/loginadmin';</script>";
            echo $str;
            exit;
        }
    }
}