<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/10/11
 * Time: 14:12
 */

namespace app\controllers;


class AtiController extends Controller
{
    private $session;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->session = Yii::$app->session;
        Yii::$app->session->open();
    }

    /*
     * 展示文章
     */
    public function actionIndex(){

        return $this->render('index');
    }

    public function addAti()
    {

    }

}