<?php

namespace app\controllers;

use yii;
use yii\web\Controller;
use app\models\User;


class SiteController extends Controller
{
    private $session;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->session = Yii::$app->session;
        Yii::$app->session->open();
    }

    /*
     * 首页
     */
    public function actionIndex()
    {
        $res = User::find()->all();
        $redis = Yii::$app->redis;
        echo $redis->get('k1');
        return $this->render('index');
    }

    /*
     * 登陆页
     */
    public function actionLogin()
    {
        $redis = Yii::$app->redis;
        $loginStatus = $redis->get();
        return $this->render('login');
    }
    /*
     * 登陆AJAX
     */
    public function actionDoLogin()
    {
        $username = $_POST['username'];
        $password = $_POST['password'];
        $user = new User();
        if(trim($username) && trim($password)){
            $where = array(
                "username"=>$username,
                "password"=>$password,
            );
            $res = $user->getOneUserInfo($where);

            if($res){
                $redis = Yii::$app->redis;
                $redis -> set(md5($res['id'].$res['password'].time()),"isLogin");
                $this->session->set("id",$res['id']);
                echo json_encode(array("msg"=>"登陆成功","code"=>10000));
                exit;
            }else{
                echo json_encode(array("msg"=>"用户名或密码错误","code"=>10001));
                exit;
            }
        }else{
            echo json_encode(array("msg"=>"请输入用户名和密码","code"=>10001));
            exit;
        }
    }

    /*
     * 注册页
     */
    public function actionReg()
    {

        return $this->render('reg');
    }

    /*
     * 注册入库
     */
    public function actionDoreg()
    {
        $username = $_POST['username'];
        $password = md5(trim($_POST['password']));
        $user = new User();
        $where = array("username"=>$username);
        $isset = $user->getOneUserInfo($where);
        if($isset){
            echo json_encode(array("msg"=>"该用户名已经存在","code"=>10000));
            exit;
        }
        $data['username'] = $username;
        $data['password'] = $password;
        $data["createtime"] = time();
        $res = $user->addUserOnce($data);
        if($res){
            echo json_encode(array("msg"=>"注册成功","code"=>10000));
            exit;
        }else{
            echo json_encode(array("msg"=>"注册失败","code"=>10000));
            exit;
        }

    }

    public function actionTest()
    {
        $res = User::find()->all();


        return $this->render('test');
    }
}
